
server:
  port: 2222
  

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.190.65:3306/db_im
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations:
    - classpath:/
        
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml    
       
       